### ISSUE TITLE
Missing list markers under some circumstances

### ISSUE THREAD

**Issue by SPiCaRiA** [Bluemoondragon07/obsidian-notation-2#6]
For the souce markdown below:

```markdown
1. a
    1. b
        1. c
            1. d
    2. 
```

Under the editor mode it will be rendered as:
<img width="372" alt="Screen Shot 2023-03-28 at 18 05 10" src="https://user-images.githubusercontent.com/11176415/228400154-65bc9144-f332-424f-9270-abb54edd9152.png">

And we lose the level 2 markers in our list! I believe this is caused by the transparent marker color:

```css
 .has-list-bullet li li, .cm-list-2 {
  --list-marker-color: transparent; /* problematic line */
  --list-bullet-border: 1px solid var(--text-normal);
  --list-bullet-size: 0.25em;
 }
```

Not sure about the incentives behind so might need more context.

Thanks!
